networks:
  distribusi_network:

services:
    ####################################################################################################
    # Nginx
    ####################################################################################################

    nginx:
        container_name: distribusi_nginx
        build:
            context: . 
            dockerfile: .docker/nginx/Dockerfile
        ports:
            - '80:80'
        volumes: 
            - ./src:/var/www
            - .docker/nginx/etc/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/conf.d/nginx/nginx.conf
        depends_on:
            - nodejs
        networks:
            - distribusi_network

         
   
    nodejs:
        container_name: distribusi_web
        restart: on-failure
        build: ./node-app
        ports:
            - '81:5000'
        environment:
            - VIRTUAL_HOST=whoami-one.localhost
        networks:
            - distribusi_network